apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: egressip-update-validation
spec:
  failurePolicy: Fail
  matchConditions:
  - expression: '("k8s.ovn.org/egressip-mark" in object.metadata.annotations) && (!has(oldObject.metadata.annotations) ||
       !("k8s.ovn.org/egressip-mark" in oldObject.metadata.annotations))'
    name: egressip-mark-annotation-update
  matchConstraints:
    resourceRules:
    - apiGroups: ["k8s.ovn.org"]
      apiVersions: ["v1"]
      operations: ["UPDATE"]
      resources: ["egressips"]
  validations:
  - expression: '(request.userInfo.username == "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-control-plane")'
    message: 'A regular user must not add "k8s.ovn.org/egressip-mark" annotation to an EgressIP custom resource.'
    reason: Invalid

---    
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: egressip-mark-annotation-validation
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: ["k8s.ovn.org"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["egressips"]
  validations:
  # Prevent creating EgressIP with the annotation
  - expression: 'request.operation != "CREATE" || !has(object.metadata.annotations) || !("k8s.ovn.org/egressip-mark" in object.metadata.annotations)'
    message: 'EgressIP resources cannot be created with the "k8s.ovn.org/egressip-mark" annotation. This annotation is managed by the system.'
    reason: Invalid
  # Prevent modifying or removing the annotation once set
  - expression: 'request.operation != "UPDATE" || !has(oldObject.metadata.annotations) || !("k8s.ovn.org/egressip-mark" in oldObject.metadata.annotations) ||
      (has(object.metadata.annotations) && ("k8s.ovn.org/egressip-mark" in object.metadata.annotations) && oldObject.metadata.annotations["k8s.ovn.org/egressip-mark"] == object.metadata.annotations["k8s.ovn.org/egressip-mark"])'
    message: 'The "k8s.ovn.org/egressip-mark" annotation cannot be modified or removed once set. This annotation is managed by the system.'
    reason: Invalid

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: egressip-update-validation-binding
spec:
  policyName: egressip-update-validation
  validationActions: [Deny]

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: egressip-mark-annotation-validation-binding
spec:
  policyName: egressip-mark-annotation-validation
  validationActions: [Deny]
